//
// Created by Julian Sommer on 02.11.23.
//

#ifndef CHESSAPPLICATION_MULTIPLAYERGAMESTATETRANSFER_H
#define CHESSAPPLICATION_MULTIPLAYERGAMESTATETRANSFER_H

class MultiplayerGameStateTransfer {
};

#endif // CHESSAPPLICATION_MULTIPLAYERGAMESTATETRANSFER_H
